### PR TITLE
feat(behavior_path_planner): pull over no stopping area

### PR DESCRIPTION
**Pull request by kosuke55**
## Description

https://github.com/autowarefoundation/autoware.universe/pull/2492

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by kosuke55** [comment]
merge after https://github.com/tier4/autoware.universe/pull/224

**Review by shmpwk — DISMISSED** [review]

**Comment by tkimura4** [comment]
(コンフリクト解消したらそのままマージしちゃって大丈夫です。他のPRも。)

**Comment by kosuke55** [comment]
@tkimura4 
すみません、pushしなおすと、approve dismissされてしまうみたいです。
設定変えること可能でしょうか？:pray:

**Review by shmpwk — APPROVED** [review]

**Comment by tkimura4** [comment]
設定かえておきました。

**Pull request merged**
