### PR TITLE
fix(external_velocity_limit_selector): revert "refactor(external_velocity_limit_selector): rework parameter (#5238)" (#6132)

### PR DESCRIPTION
**Pull request by h-ohta**
## Description

backport from https://github.com/autowarefoundation/autoware.universe/pull/6132

## Related Links
https://tier4.atlassian.net/browse/RT0-30609

## Tests performed

I confirmed in https://tier4.atlassian.net/browse/RT0-30609?focusedCommentId=155732

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by 0x126 — APPROVED** [review]
LGTM !

**Comment by 0x126** [comment]
I checked https://tier4.atlassian.net/browse/RT0-30609?focusedCommentId=155732

**Comment by h-ohta** [comment]
@mergifyio backport beta/v0.19.2

**Comment by h-ohta** [comment]
@Mergifyio backport beta/v0.19.2

**Pull request merged**
