### PR TITLE
feat(lane_change): cherry-pick lane change commits to beta/v0.29.0

### PR DESCRIPTION
**Pull request by zulfaqar-azmi-t4**
## Description

Cherry-pick lane change module.

Several part of lane change module needs to be refactored to improve the processing time.

#### processing time improvement
[refactor(lane_change): update lanes and its polygons only when it's updated](https://github.com/tier4/autoware.universe/commit/3e4d2d0310cf358ca9ab5797adeaf0f45a224642)
[refactor(lane_change): check start point directly after getting start point #8357](https://github.com/tier4/autoware.universe/commit/70425d535dc32299b79c04ec78e0542b2049be7f)
[fix(lane_change): skip path computation if len exceed dist to terminal start #8359](https://github.com/tier4/autoware.universe/pull/1441/commits/a1d4bfef566bfe2bb864cbfa39110ab0cd72a53d)
[fix(lane_change): skip generating path if lane changing path is too long #8362](https://github.com/tier4/autoware.universe/commit/2e4164c92b397b85b960a0bbea9a0c583b46f173)
[fix(lane_change): skip generating path if longitudinal distance difference is less than threshold #8363](https://github.com/tier4/autoware.universe/commit/b8306187b35d5785b8bafcf42387ee02cf66528b)
[refactor(lane_change): separate leading and trailing objects #8214](https://github.com/tier4/autoware.universe/commit/8314f3820be73ef78443d615f0934e1b1d63d2d4)

#### improving lane change behavior

[fix(lane_change): delay lane change cancel #8048](https://github.com/tier4/autoware.universe/pull/1441/commits/ab60a5b9add673d6187c12fd009ba6a497008d63)
[fix(lane_change): filtering object ahead of terminal #8093](https://github.com/tier4/autoware.universe/pull/1441/commits/6d38b7f37f6ff6cbc384a221691db601469c112c)
[fix(lane_change): relax finish judge #8133](https://github.com/tier4/autoware.universe/pull/1441/commits/4a1864a4354813b5407c9c9957b8fda73690da78)
[feat(lane_change): use different rss param to deal with parked vehicle #8316](https://github.com/tier4/autoware.universe/pull/1441/commits/dde26ce72e73936b05fd3637f63bb3d204acef67)
[fix(lane_change): do not cancel when approaching terminal start #8381](https://github.com/autowarefoundation/autoware.universe/pull/8381)
[fix(lane_change): moving object is filtered in the extended target lanes #8218](https://github.com/autowarefoundation/autoware.universe/pull/8218)

#### Bug fix
[fix(lane_change): fix invalid doesn't have stop point #8470](https://github.com/autowarefoundation/autoware.universe/pull/8470)

## Related links

https://github.com/tier4/autoware_launch/pull/537
**Parent Issue:**

- Link

## Notes for reviewers

None.

## Interface changes

None.

#### Additions and removals

| Change type   | Parameter Name | Type     | Default Value | Description       |
|:--------------|:---------------|:---------|:--------------|:------------------|
| Added     | `finish_judge_lateral_angle_deviation` | `double` | `1.0`         | lateral angle threshold to determine lane change completion |
| Added     | `parked.expected_front_deceleration` | `double` | `-1.0`         | The front object's maximum deceleration when the front vehicle perform sudden braking |
| Added     | `parked.expected_rear_deceleration` | `double` | `-2.0`         | The rear object's maximum deceleration when the rear vehicle perform sudden braking.  |
| Added     | `parked.rear_vehicle_reaction_time` | `double` | `1.0`         | The reaction time of the rear vehicle driver which starts from the driver noticing the sudden braking of the front vehicle until the driver step on the brake. |
| Added     | `parked.rear_vehicle_safety_time_margin` | `double` | `0.8`         | The time buffer for the rear vehicle to come into complete stop when its driver perform sudden braking. |
| Added     | `parked.lateral_distance_max_threshold` | `double` | `1.0`         | The lateral distance threshold that is used to determine whether lateral distance between two object is enough and whether lane change is safe. |
| Added     | `parked.longitudinal_distance_min_threshold` | `double` | `3.0`         | The longitudinal distance threshold that is used to determine whether longitudinal distance between two object is enough and whether lane change is safe. |
| Added     | `parked.longitudinal_velocity_delta_time` | `double` | `0.0`         | The time multiplier that is used to compute the actual gap between vehicle at each predicted points (not RSS distance) |
| Added     | `skip_process.longitudinal_distance_diff_threshold.prepare` | `double` | `1.0`         | prepare longitudinal distance threshold to skip path planning |
| Added     | `skip_process.longitudinal_distance_diff_threshold.lane_changing` | `double` | `1.0`         | lane changing longitudinal distance threshold to skip path planning |

#### Modifications

| Version | Parameter Name   | Type     | Default Value | Description       |
|:--------|:-----------------|:---------|:--------------|:------------------|
| Old     | `finish_judge_lateral_threshold` | `double` | `0.2`         | lateral threshold to determine lane change completion |
| New     | `finish_judge_lateral_threshold` | `double` | `0.1`         | lateral threshold to determine lane change completion |

## Effects on system behavior

None.

### CODE REVIEW

**Comment by Naophis** [comment]
@zulfaqar-azmi-t4 
Could you please explain the purpose of this PR?
I've looked through the commit list, and it seems to be mainly refactoring. Is that correct?

**Review by shmpwk — APPROVED** [review]
@zulfaqar-azmi-t4 cc. @Naophis
Thank you so much! I'd like to merge this after v0.46.0 release this week. Until that let me change this PR to draft 🙏

**Comment by zulfaqar-azmi-t4** [comment]
@Naophis @shmpwk 
These PR is necessary for lane change computation time improvement, therefor I really hope it got merged before the release.

I cherry-pick all of them at once to to avoid fixing current and future conflicts.

However, if you feel I dont need to cherry-pick them all, then I can select the necessary changes.

**Comment by zulfaqar-azmi-t4** [comment]
@Naophis 

> Could you please explain the purpose of this PR?
> I've looked through the commit list, and it seems to be mainly refactoring for lane change function. Is that correct?

I have updated the explanation in the thread. To summarize, the most biggest and important change is the processing time improvement when generating lane change path. The change is made possible by the refactoring of lane change task.

**Comment by saka1-s** [comment]
@shmpwk @Naophis 
A bug([slack](https://star4.slack.com/archives/C074CCKN35E/p1723601310650599)) has been found in the LC module.
Azu-san has prepared the fix PR, and this PR is assumed to be merged before.　
If there doesn't seem to be any issues with this PR, would it be possible to include it in v0.29.0?

**Comment by saka1-s** [comment]
I will check evaluator result.

**Comment by zulfaqar-azmi-t4** [comment]
@shmpwk @Naophis 
I have two additional PR that will be helpful which I already tested in an experiment a week ago.

It is okay for me to add them in this cherry-pick?
https://github.com/autowarefoundation/autoware.universe/pull/8381
https://github.com/autowarefoundation/autoware.universe/pull/8218

**Comment by shmpwk** [comment]
@zulfaqar-azmi-t4 @Naophis @saka1-s 

xx1 v0.46.0(universe v0.29.1) has been released today.

So we xx1 is ready to merge this great cherry pick.
Also, these PRs look nice for me and I eager to cherry pick them.
autowarefoundation#8381
autowarefoundation#8218

**Comment by zulfaqar-azmi-t4** [comment]
@shmpwk 
That is great! I have cherry-picked them.

**Comment by Naophis** [comment]
@zulfaqar-azmi-t4  cc: @saka1-s 
thanks for informed me.
I wanna use cherry pick them in X2 v3.1.0 , and please change Draft to PR.

**Pull request merged**
