### PR TITLE
feat(hazard_lights_selector): turn on hazard lights from mrm comfortable stop operator

### PR DESCRIPTION
**Pull request by mkuri**
## Description

https://tier4.atlassian.net/browse/T4PB-22513

Add hazard_lights_selector so that hazard lights can be directed from nodes other than behavior_path_planner

**Related PR**
- https://github.com/tier4/autoware_launch.x2/pull/258

**Before**
hazard_light_cmd-Before drawio

**After**
hazard_light_cmd-After drawio

**Test**
緩停止MRMを発動させて`/planning/hazard_lights_cmd`のcommandが2 (=ENABLE)をpublishすること

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by TomohitoAndo — APPROVED** [review]
I confirmed this works.
https://user-images.githubusercontent.com/11865769/225789692-5afe523e-892a-45f9-828e-e49e64b2426c.mp4

**Comment by TomohitoAndo** [comment]
@mkuri 
I think this is irrelevant with this PR, I found that the vehicle sometimes can't stop with MRM comfortable stop. :pleading_face: 

https://user-images.githubusercontent.com/11865769/225790191-9edd6d46-0454-494a-804f-f764b4b051c3.mp4

**Comment by mkuri** [comment]
@TomohitoAndo 
> I think this is irrelevant with this PR, I found that the vehicle sometimes can't stop with MRM comfortable stop.
I'll fix this issue in a separate PR

**Comment by TomohitoAndo** [comment]
pre-commit.ci run

**Comment by TomohitoAndo** [comment]
@mkuri 
I added pre-commit fixes and this can be merged now.

**Pull request merged**
