### PR TITLE
feat(lidar_transfusion): update TransFusion-L model (#7890)

### PR DESCRIPTION
**Pull request by scepter914**
## Description

- cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/7890

## Related links

**Parent Issue:**

- Link

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Review by amadeuszsz — APPROVED** [review]
LGTM

**Comment by knzo25** [comment]
@scepter914 
Will this PR be merged ? (otherwise, it may be better to close it or put it as a draft)

**Comment by scepter914** [comment]
@knzo25 

Yes.

I'm sorry that I didn't write status.
This PR waits for integration test of SI team for now, so after that I'll merge.

**Comment by shmpwk** [comment]
@scepter914 @amadeuszsz @knzo25 
We are so sorry that we could't apply this transfusion-l model in beta/v0.29.0 (pilot-auto.xx1 v0.46.* release)
Let's try this in xx1 v0.47.0 release :pray:

**Pull request closed without merging**
