### PR TITLE
fix: use TRAFFIC_LIGHT_CAMERA_NUMBER env var

### PR DESCRIPTION
**Pull request by dkoldaev**
## Description

to serve JT4 with 2 TL cameras

## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by shmpwk** [comment]
@dkoldaev 
Thank you for the PR.
How to set `TRAFFIC_LIGHT_CAMERA_NUMBER` ? 
Creating env file like [set_autoware_env](https://github.com/tier4/autoware_ecu_system_setup/tree/main/roles/set_autoware_env) ? Or can we specify it in [individual_params](https://github.com/tier4/autoware_individual_params.jpntaxi/tree/main/individual_params/config/4) though it is not env file.

**Comment by dkoldaev** [comment]
> @dkoldaev Thank you for the PR. How to set `TRAFFIC_LIGHT_CAMERA_NUMBER` ? Creating env file like [set_autoware_env](https://github.com/tier4/autoware_ecu_system_setup/tree/main/roles/set_autoware_env) ? Or can we specify it in [individual_params](https://github.com/tier4/autoware_individual_params.jpntaxi/tree/main/individual_params/config/4) though it is not env file.

I think it would be the best to add to the JT4 env file for autoware ECU. Do we have a repo for it?

**Comment by shmpwk** [comment]
@dkoldaev 
Nothing but autoware.env and vehicle.env set in [set_autoware_env](https://github.com/tier4/autoware_ecu_system_setup/tree/main/roles/set_autoware_env).

**Comment by dkoldaev** [comment]
> @dkoldaev Nothing but autoware.env and vehicle.env set in [set_autoware_env](https://github.com/tier4/autoware_ecu_system_setup/tree/main/roles/set_autoware_env).

I can't find vehicle.env. Is it only created on the vehicle itself and not committed to any repo?

**Comment by shmpwk** [comment]
@dkoldaev 
Here is the inside of the vehicle.env.
```
vehicle_id: default
vehicle_model: lexus
sensor_model: aip_xx1
```
https://github.com/tier4/autoware_ecu_system_setup/blob/main/roles/set_autoware_env/defaults/main.yaml#L6-L9


`ecu_setup.yaml` overrides those files here.
https://github.com/tier4/pilot-auto.xx1/blob/34182c32d82ee719c101da523c08fa4e75d84613/ansible/playbooks/vars/ecu_setup.yaml#L47-L51

Currently, each vehicle_id is set manually by FI team.

**Comment by yukkysaito** [comment]
It would be better to set this value in aip_launcher, not in an environment variable.

**Comment by dkoldaev** [comment]
> It would be better to set this value in aip_launcher, not in an environment variable.

this m

> It would be better to set this value in aip_launcher, not in an environment variable.
> This is because the value is determined by the type of ai pilot rather than being body specific.

This makes sense. But also this PR is for an old version of XX1 pilot auto (v0.44) to take care of JT4. From version v0.45 onward the launcher takes care of this param.

**Comment by shmpwk** [comment]
@yukkysaito 
I talked with Dmitrii-san that this PR is temporal one and only for JT#4.
After merging this, we will quickly tag release this and won't use this for other Japantaxi anymore.
In the long run, we will consider the fundamental solution such as aip individual parameter which Saito-san suggested.

**Comment by shmpwk** [comment]
@dkoldaev @yukkysaito 
Long-term plan such as reading aip individual param will be worked on by Dmitrii-san in the following ticket.
https://tier4.atlassian.net/browse/RT0-31420

**Review by shmpwk — APPROVED** [review]

**Comment by dkoldaev** [comment]
@shmpwk thank for sorting out the future plans. What should I do with CI? I can see that pre commit is already failing on the branch

**Comment by shmpwk** [comment]
Hmm :thinking: I don't have an idea... But we can merge ignoring the required pre-commit.ci anyway.

**Pull request merged**
