### PR TITLE
feat(launch): enable glog to print stack trace autonatically when the process die in planning/control modules

### PR DESCRIPTION
**Pull request by TakaHoribe**
## Description

glogの有効化。ノードが死んだときに自動でstack traceが印字されるので、解析が楽になります！

関連PR：
- https://github.com/autowarefoundation/autoware.universe/pull/4714
- https://github.com/autowarefoundation/autoware.universe/pull/4745
- https://github.com/autowarefoundation/autoware.universe/pull/4746

## Tests performed

Now working:
- [x] xx1での動作確認 in psim
- [ ] 処理負荷が上がらないことの確認 in psim

## Effects on system behavior

ノードが死んだときに自動でstack traceが印字される

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by takayuki5168 — APPROVED** [review]

**Comment by TakaHoribe** [comment]
ちょっと処理不可が気になるのでマージ待ってください

**Comment by TakaHoribe** [comment]
smootherのCPU利用率：
上がPR前（node exe）、下がPR後（コンテナ）。特に変化なし。
image

**Comment by TakaHoribe** [comment]
mission plannerとsmootherに関しては、launch変更によるrosparamに変化が無いことを確認済み。

**Comment by TakaHoribe** [comment]
@tkimura4 こちら側はマージreadyです！

**Pull request merged**
