### PR TITLE
ci(dispatch-release-note): use Github Apps instead of GIHUB_TOKEN

### PR DESCRIPTION
**Pull request by shmpwk**
## Description

We mostly cannot dispatch workflow with GITHUB_TOKEN.
Instead, we often use Github Apps for organization authorization.
This PR is a substitue for https://github.com/tier4/autoware.universe/pull/314

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by shmpwk** [comment]
@kenji-miyake 
Could you check the authorization scope of Github Apps if it can trigger the other repository(=https://github.coc/tier4/update-release-notes)?  
Currently, the CI is failed because of 404 https://github.com/tier4/autoware.universe/actions/runs/4400367753/jobs/7705601385

**Comment by kenji-miyake** [comment]
@shmpwk I've asked the org admin to add you to the App admin.

**Comment by shmpwk** [comment]
@kenji-miyake 
I succeeded to add read and write access for Actions and Contents.
https://github.com/organizations/tier4/settings/apps/tier4-autoware-public-bot/permissions
However the dispatch is still failed.
Do you have an insight for this?

**Comment by kenji-miyake** [comment]
@shmpwk Mm, I'm sorry I have no idea. :cry:

**Comment by kenji-miyake** [comment]
@shmpwk I think your request weren't approved yet. Could you try it again?

**Comment by shmpwk** [comment]
Thank you for your approval, but still it is failed.
I continue to investigate the cause of the 404.

**Comment by shmpwk** [comment]
@kenji-miyake 
I confirmed that dispatch succeeded !
- dispatch from
  - https://github.com/tier4/autoware.universe/actions/runs/4410875614/jobs/7730258877- 
- dispatched workflow
  - https://github.com/tier4/update-release-notes/actions/runs/4411598287

The cause of the problem is that I haven't completed to install Github Apps at dipatched workflow.

Thank you for your help!

**Comment by shmpwk** [comment]
Thank you for modifying spell

**Comment by shmpwk** [comment]
I mistakenly merged the tier4/main branch and ask many people to review.
Now I reset the commits but sorry for bothering you.

**Comment by shmpwk** [comment]
I've messed up commanding the git operations, but it looks like everything is ready to go now.

**Review by kenji-miyake — APPROVED** [review]

**Pull request merged**
